name: "Release"

on:
  push:
    tags:
      - "*.*"

jobs:
  release:
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af
        with:
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@6720f05bc48b77f96918929a9019fb2203ff71f8

      - name: "Build"
        run: cargo build

      - name: "Test"
        run: cargo test

      - uses: katyo/publish-crates@2ffe86caafd7b9be8c4eb795ffdb2dd41ae8564c
        with:
          registry-token: ${{ secrets.CRATES_TOKEN }}
